---
version: '3'
services:
    api:
        build:
            context: .
            args:
                API_VSN: ${API_VSN}
                REGULAR_CHAMPIONSHIP_VSN: ${REGULAR_CHAMPIONSHIP_VSN}
        expose:
            - "80"
        command: "/opt/app/bin/start_server foreground"
        networks:
            - backend
    proxy:
        build: ./haproxy
        networks:
            - backend
        depends_on:
            - api
        ports:
            - "80:80"
        links:
            - api:api
networks:
    backend:
